---

- name: Grafana Setup
  hosts: grafana
  gather_facts: false
  remote_user: root
  sudo: yes

  tasks:
    - name: Setting "SELINUX=disabled"
      shell: |
        echo "SELINUX=disabled" > /etc/sysconfig/selinux
        echo "SELINUXTYPE=targeted" >> /etc/sysconfig/selinux

    - name: Creating Grafana Repository"
      shell: |
        echo "[grafana]" > /etc/yum.repos.d/grafana.repo
        echo "name=grafana" >> /etc/yum.repos.d/grafana.repo
        echo "baseurl=https://packages.grafana.com/oss/rpm" >> /etc/yum.repos.d/grafana.repo
        echo "repo_gpgcheck=1" >> /etc/yum.repos.d/grafana.repo
        echo "enabled=1" >> /etc/yum.repos.d/grafana.repo
        echo "gpgcheck=1" >> /etc/yum.repos.d/grafana.repo
        echo "gpgkey=https://packages.grafana.com/gpg.key" >> /etc/yum.repos.d/grafana.repo
        echo "sslverify=1" >> /etc/yum.repos.d/grafana.repo
        echo "sslcacert=/etc/pki/tls/certs/ca-bundle.crt" >> /etc/yum.repos.d/grafana.repo

    - name: Installing Grafana and its Font Packages
      yum:
        name: 
          - grafana
          - fontconfig
          - freetype*
          - urw-fonts
        state: present

    - name: Restarting Grafana Service
      shell: |
        systemctl enable grafana-server
        systemctl restart grafana-server
        firewall-cmd --zone=public --add-port=3000/tcp --permanent
        firewall-cmd --reload
