---
- name: Install the node_exporter service
  hosts: director
  become: yes

  tasks:
   - name: install ansible
     yum:
       name: ansible
       state: present


   - name: download ansible playbooks 
     unarchive:
      src: "https://codeload.github.com/zeeshan-07/Ceph-ansible-playbooks/zip/master"
      dest: /root/
      remote_src: yes
   - name: read the hosts file
     shell: cat /etc/ansible/hosts
     register: string

   - name: Task that only happens if the node exporter does not exists in /etc/ansible/hosts file
     blockinfile:
       path: /etc/ansible/hosts
       block: |
         [node_exporter]
         nova0 ansible_ssh_host=nova0 ansible_ssh_pass=Dell0SS! ansible_ssh_user=heat-admin ansible_become_method=enable
         nova1 ansible_ssh_host=nova1 ansible_ssh_pass=Dell0SS! ansible_ssh_user=heat-admin ansible_become_method=enable
         nova2 ansible_ssh_host=nova2 ansible_ssh_pass=Dell0SS! ansible_ssh_user=heat-admin ansible_become_method=enable
         cntl0 ansible_ssh_host=cntl0 ansible_ssh_pass=Dell0SS! ansible_ssh_user=heat-admin ansible_become_method=enable
         cntl1 ansible_ssh_host=cntl1 ansible_ssh_pass=Dell0SS! ansible_ssh_user=heat-admin ansible_become_method=enable
         cntl2 ansible_ssh_host=cntl2 ansible_ssh_pass=Dell0SS! ansible_ssh_user=heat-admin ansible_become_method=enable
         str0 ansible_ssh_host=str0 ansible_ssh_pass=Dell0SS! ansible_ssh_user=heat-admin ansible_become_method=enable
         str1 ansible_ssh_host=str1 ansible_ssh_pass=Dell0SS! ansible_ssh_user=heat-admin ansible_become_method=enable
         str2 ansible_ssh_host=str2 ansible_ssh_pass=Dell0SS! ansible_ssh_user=heat-admin ansible_become_method=enable
     when: string.stdout.find('[node_exporter]') == -1
   
   - name : setup ansible host file
     copy:
       content : |
                 [node_exporter]
                 cntl[0:2]   ansible_ssh_user=root
                 nova[0:2]   ansible_ssh_user=root
                 stor[0:2]   ansible_ssh_user=root
       dest : /etc/ansible/hosts
   
   - name : Run ansible playbook
     shell : |
             ansible-playbook /root/Ceph-ansible-playbooks-master/setup_nodexporter.yml -i /etc/ansible/hosts
