---
- name: Create a environment
  hosts: hosts
  tasks:
    - name: create network and subnet
      shell: |
             source /home/osp_admin/r60rc
             openstack network create network1
             openstack subnet create subnet1 --network network1 --subnet-range 192.168.50.0/24
      register: print_output
    - debug: var=print_output

    - name: create subnet
      shell: |
             source /home/osp_admin/r60rc
             openstack router create router1
             openstack router add subnet router1 subnet1
             openstack router set router1 --external-gateway public
      register: print_output
    - debug: var=print_output

#    - name: create ssh-key
#      shell: |
#             source /home/osp_admin/r60rc
#             openstack keypair create ssh-key > /home/osp_admin/ssh-key.pem
#      register: print_output
#    - debug: var=print_output
